### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by irfanismaya20** [eveningkid/react-native-popable#17]
![Simulator Screen Shot - iPhone 11 - 2021-07-18 at 15 27 03](https://user-images.githubusercontent.com/12542123/126060846-5e26aa49-98a0-4259-8e29-377a2daff7f2.png)

<Popable
    content={
    <View
    style={{
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white'
    }}
    >
    <Text>{mtdlegend}</Text>
    </View>
}>
    <Text style={{ 
        fontFamily:'MaisonNeue-Bold', 
        fontSize: 12,
        color: mtd_color,
        textTransform: 'uppercase'
    }}>{mtd}</Text>
</Popable>

**Comment by eveningkid** [comment]
Hi,

I'll need the full section using `Popable` to understand where the issue is coming from.

Good day

**Comment by eveningkid** [comment]
Hi,

Since I couldn't reproduce the issue you mentioned and haven't heard back from you, I'll close the issue for now.

Feel free to comment again and provide a full example if the issue has persisted.
