### ISSUE TITLE
Popable not working in landscape view in iOS

### ISSUE THREAD

**Issue by Udayan-KS** [eveningkid/react-native-popable#19]
Issue scenario: When the device is in landscape mode click on popable element, it automatically rotates your screen to portrait and display the popable
For android it's working fine

**Comment by eveningkid** [comment]
Hi,

Could you provide a working example with Snack?

This will help me to work on this issue together.

Have a great day

**Comment by Udayan-KS** [comment]
Hi @eveningkid 

i have created a sample snack.

Please do try on an iOS device with landscape orientation.

[Sample popable ](https://snack.expo.dev/@udayantv/popable-sample-)

**Comment by Udayan-KS** [comment]
The issue is caused due usage of modal component for popable. Since iOS support portrait mode by default for modal. You have to make use of extra prop **supportedOrientations**

**Comment by eveningkid** [comment]
Hey,

Thanks a lot for the example. I couldn't try it though since my screen wouldn't rotate at all for some reason.

Now theoretically, we should add all the available orientations (i.e. not just the default `portrait`), right?

**Comment by Udayan-KS** [comment]
Yes you should add these values ['portrait', 'portrait-upside-down', 'landscape', 'landscape-left', 'landscape-right'] to the supportedOrientations prop inside model component

**Comment by eveningkid** [comment]
The update is available in `0.4.3` :)

Thanks for reporting the issue, I hope this will fix it.

Have a great day!
