### ISSUE TITLE
Idea: auto placement

### ISSUE THREAD

**Issue by nandorojo** [eveningkid/react-native-popable#2]
I think it would be useful to re-align the popover if the proposed alignment doesn't fit within the screen.

I envision something like this:

![Popable alignment](https://user-images.githubusercontent.com/13172299/111819896-3f75a780-88b7-11eb-8c0d-c4e5ade58233.png)

The first situation would actually render the second one. However, if you pass something like `strictPlacement`, then it doesn't do that. 

Let me know what you think. Really excited about this project. Popovers are an important addition to RN, as I mentioned [here](https://moti.fyi/#contributing-to-react-native). I'm glad to see it's being solved.

**Comment by eveningkid** [comment]
Right, good idea.

And likewise, it should send it to the bottom if there's not enough room at the top.

I'll work on it shortly and update this issue

**Comment by yusufff** [comment]
Popper-core's placement logic could be an inspiration.

https://github.com/popperjs/popper-core

**Comment by eveningkid** [comment]
Thank you @yusufff for sharing. Popper seemed really hardcore on keeping the popover on screen...

For now, Popable will just invert the position if there's not enough room at the given position.

I think it's great since this library should remain minimal.

Again, thanks for raising the issue, it's better this way!

**Comment by nandorojo** [comment]
Thoughts on default behavior? I imagine it shouldn't be strict by default, but depends on how much "magic" you think it should have. If strict is default true, I'll just wrap this in my app and make it false.

**Comment by eveningkid** [comment]
Agreed, just realised [it's actually false by default](https://github.com/eveningkid/react-native-popable/blob/main/src/Popable.tsx#L47) but I stated it's true in the readme!
