### ISSUE TITLE
Add named components

### ISSUE THREAD

**Issue by nandorojo** [eveningkid/react-native-popable#3]
https://github.com/eveningkid/react-native-popable/blob/49515ac06b393bfeb8c34358f3cb901c47e76a5b/src/Popable.tsx#L27

Next.js fast refresh breaks with anonymously named components. It could be solved with `export default function Popable`.

This also has[ other implications](https://twitter.com/dan_abramov/status/1255229440860262400?lang=en) for debugging.

I can PR this if you'd like.

**Comment by eveningkid** [comment]
Definitely, please do and I'll merge it when it's ready!

**Comment by eveningkid** [comment]
Just worked on it while I was at it: https://github.com/eveningkid/react-native-popable/pull/5

Would that work you think?
