### ISSUE TITLE
Clipped popable edges for left/right positioning

### ISSUE THREAD

**Issue by Benjamiiiin** [eveningkid/react-native-popable#6]
Hi there, this is friggitydingo, came here from Reddit :P I've been trying out the component, I like it a lot! 

When I tried the left/right positions, however, with more several words of text content, I found the edge of the component was clipping off like in the image I attached.

This can be reproduced in your example app with the following:
`<Popable content="See profile and tell me what you think" position='left' strictPosition={true}>`

I was able to fix this for myself by commenting out the `overflow: 'hidden'` line in the _container_ style of react-native-popable/src/Popover.tsx - although I'm not sure if that will adversely affect other things.

Thanks!

![popable](https://user-images.githubusercontent.com/24235416/111891823-e427ee80-8a49-11eb-8b94-5c7541f4431f.png)

**Comment by eveningkid** [comment]
Thank you for sharing Benjamin!

I will take a look at it later, this should definitely be fixed shortly.

I'll keep you updated :)

**Comment by eveningkid** [comment]
This should hopefully be fixed in `0.2.0`!

Hope this works out better this time.

Just let me know if you find anything else :)

Have a great day!

**Comment by Benjamiiiin** [comment]
Nice work, thanks! I'll let you know if anything else pops up (pardon the pun)

**Comment by eveningkid** [comment]
(good one :))
