### ISSUE TITLE
Live demo?

### ISSUE THREAD

**Issue by impressivewebs** [eveningkid/react-native-popable#9]
Do you have a live demo somewhere to link to? I don't see one in the docs.

**Comment by eveningkid** [comment]
Hey Louis,

That's a very good idea, I'll make one soon!

There is an undergoing important feature I'm working on right now.
It should be ready tomorrow, so I'll make an Expo Snack when the new version is released.

I'll update this once it's ready.

Have a great day :)

**Comment by eveningkid** [comment]
I just updated the README, you can quickly try any property using this [sandbox](https://snack.expo.io/dmLOIiVHy).

If you have a few ideas for examples I could add to the playground, let me know.

I'll close the issue for now but feel free to reply

**Comment by impressivewebs** [comment]
@eveningkid That's great, thanks! I do [a newsletter](https://webtoolsweekly.com/) on tools so I wanted to include it, but was hoping for a demo page before I did.
